name: ReadFaster
options:
  bundleIdPrefix: com.readfaster
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  createIntermediateGroups: true

packages:
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    from: "0.9.0"
  SwiftSoup:
    url: https://github.com/scinfu/SwiftSoup.git
    from: "2.6.0"

settings:
  base:
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"

targetTemplates:
  App:
    type: application
    sources:
      - ReadFaster
    dependencies:
      - package: ZIPFoundation
      - package: SwiftSoup
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.readfaster.app
        PRODUCT_NAME: Read Faster
        INFOPLIST_FILE: ReadFaster/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: false
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    entitlements:
      path: ReadFaster/Resources/ReadFaster.entitlements

targets:
  ReadFaster-iOS:
    templates:
      - App
    platform: iOS
    settings:
      base:
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: true

  ReadFaster-macOS:
    templates:
      - App
    platform: macOS
    settings:
      base:
        ENABLE_HARDENED_RUNTIME: true

schemes:
  ReadFaster-iOS:
    build:
      targets:
        ReadFaster-iOS: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  ReadFaster-macOS:
    build:
      targets:
        ReadFaster-macOS: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
